apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/fvergnes/.asdf/installs/kompose/1.34.0/bin/kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  template:
    metadata:
      annotations:
        kompose.cmd: /home/fvergnes/.asdf/installs/kompose/1.34.0/bin/kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: adminer
    spec:
      containers:
        - image: adminer:4.8.1
          name: adminer
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/fvergnes/.asdf/installs/kompose/1.34.0/bin/kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: adminer
