apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
spec:
  containers:
    - name: broker
      image: confluentinc/cp-kafka:8.1.0
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        - name: kafka-secrets
          mountPath: /etc/kafka/secrets
    - name: akhq
      image: tchiotludo/akhq:0.26.0
      ports:
        - containerPort: 8080
      env:
        - name: AKHQ_CONFIGURATION
          value: |
            akhq:
              connections:
                docker-kafka-server:
                  properties:
                    bootstrap.servers: "broker:29092"
  volumes:
    - name: kafka-data
      hostPath:
        path: /srv/podman/python-otel-project-demo/kafka-data
    - name: kafka-secrets
      hostPath:
        path: /srv/podman/python-otel-project-demo/kafka-secrets
