apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/fvergnes/.asdf/installs/kompose/1.34.0/bin/kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order
  template:
    metadata:
      annotations:
        kompose.cmd: /home/fvergnes/.asdf/installs/kompose/1.34.0/bin/kompose -f docker-compose.yml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: order
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:yourpassword@postgres:5432/mydatabase
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel:4317
            - name: OTEL_LOGS_EXPORTER
              value: otlp, console
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: "true"
            - name: OTEL_PYTHON_LOG_CORRELATION
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: order
            - name: OTEL_TRACES_EXPORTER
              value: otlp
          image: order
          name: order
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/fvergnes/.asdf/installs/kompose/1.34.0/bin/kompose -f docker-compose.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: order
  name: order
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 5000
  selector:
    io.kompose.service: order
